// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PageParms struct {
	Limit  *int `json:"limit"`
	Offset *int `json:"offset"`
}

type PostsList struct {
	TotalCount int    `json:"totalCount"`
	Posts      []Post `json:"posts"`
}
